### PR TITLE
Tasks features

### PR DESCRIPTION
**Pull request by baldez300**

### CODE REVIEW

**Comment by viettrung2103** [comment]
Application Overview Understanding
- Your readme is detail and has good instruction to follow.
Code Structure and Quality
- in `routes.py`,  the code name is descriptive and self-explaining.
- In `templates` folders,  you have many templates now so I think you can seperate into their own features
Commit Analysis
- Commit message is details, by reading the commit, I understand what you want to do with each commit
Communication and Documentation
- As I have mentioned above, the readme is details and easy to follow
- However, I think you can try to create a user Story in Issues first, and create mini tasks +the estimated time to do each of them and for this User Story. Afterward, you can code and commit following these mini tasks without worrying you missing anything. The last benefit and you can measure and log the actual time you need to do for each task/feature.
Suggestions for Improvement
- My only suggestion to you is try to slice your templates into their own groups so it will be easy to manage and maintain.
All of all, your project is a very good. and I have learned many thing about Flask by looking at your project. Thank you

**Comment by baldez300** [comment]
Thank you for the positive feedback and constructive suggestions! I appreciate your detailed review of the readme, code structure, commit messages, and communication/documentation. I'll definitely consider your advice on creating user stories and slicing templates for better project management. I'm glad to hear that you've found value in the project and learned from it. Much appreciated!

**Comment by aikkuvo333** [comment]
Code review week 3

- VERY informative commit messages, the most informative as far as i've seen compared to all the other projects

- you're handling the negatives first in functions and the functions do not contain nested logic

- hard to find improvements, since the code seems pretty clear to me but if I had to say something, then some of the comments are useless since ur variables and function names are pretty clear (for example in routes.py lines 82, 89, 99)

Keep up the good work!

**Comment by baldez300** [comment]
Thank you for your insightful review! 
Your recognition of the informative commit messages and clear function organization is motivating.

**Pull request merged**
