### PR TITLE
Implementing user-friendly error handling for better UX

### PR DESCRIPTION
**Pull request by baldez300**
Implemented user-friendly error handling in the registration process to inform users when attempting to register with an email that is already in use.

Enhanced login functionality, the system now display informative message to users, indicating whether their login attempt was unsuccessful due to incorrect credentials.

### CODE REVIEW

**Comment by valtat** [comment]
**Exercise Week 6: Project Week 4 review by valtat**

Everything looks nice in your pull request, from the commits to the actual code. Good job!

A couple things: I really like your readme. The step by step guide is written very well, and I have no doubt that even an user with little experience can follow it and get everything up and running. In your latest readme commit, you explain how to clear up migration history and some mariadb commands for both windows and mac. Like I said, it's very well written and informative. However, have you thought about including a why to the migration history cleanup? Some users might not know why they should do that. On that same note, maybe you could add reference about MariaDB to those users in the readme who don't know what it is or how to install it. But of course, most likely people who would use this project already have it installed or know about it. Just a thought that entered my mind.

The commit about adding user friendly error handling is spot on in my opinion. I think you handle the message and the potential error of an existing user gracefully - good work. There is a rollback and clear message so no changes to the database will be made and the error message the user gets leaves nothing to the imagination.

**Comment by baldez300** [comment]
Thank you for the positive feedback! I appreciate your thorough review. 
Regarding the migration history cleanup, it's a great suggestion to include a "why" for users. I'll add an explanation to make it more comprehensive. Also, I'll consider adding a brief reference to MariaDB for users unfamiliar with it. 
Your insights are valuable, and I'll make these enhancements to ensure a better user experience. 
Thanks again!

**Comment by TaiNguyen2407** [comment]
I think you have a great PR, even with 2 commit messages but I still see what you are trying to implement. Great work. 

Similar to @valtat, I like the detailed readme, I think normal users would be able to follow the readme well, not to mention developers or tech people. Great job with the readme. 

One question though, does the readme instructions apply to other database systems as well (e.g Postgresql, Dynamodb)

Keep up the good work!

**Comment by baldez300** [comment]
Thank you for the positive feedback on my PR! I appreciate your acknowledgment of the detailed **README**. 
Regarding your question @TaiNguyen2407 , the instructions are primarily for **SQLite**, but adapting them to other databases like (eg **Postgresql, Dynamodb**) shouldn't be a big change, although I haven't tried it yet. 
Thanks again!

**Pull request merged**
